### ISSUE TITLE
onConnect never gets called

### ISSUE THREAD

**Issue by jubalh** [davidlazar/PircBot#2]
Hi,
I looked at https://github.com/davidlazar/ReminderBot/blob/master/src/org/jibble/reminderbot/ReminderBot.java for an example, but somehow my onConnect() etc. methods never get calles. Do I have to register them somehow?

**Comment by MiningMark48** [comment]
Try this:

public void onConnect(String channel, String sender, String login, String hostname, String message){

```
    }
```
