### ISSUE TITLE
Some way of reconnect if the Bot times out

### ISSUE THREAD

**Issue by MiningMark48** [davidlazar/PircBot#3]
Is there a way I can automatically have my bot join back if he times out?

My bot: https://github.com/MiningMark48/BoxBot/

**Comment by JamoBox** [comment]
What do you mean by if it times out? If you mean when it loses connection to the server and you want to attempt to reconnect, then that should be simple as checking the PING heartbeats sent by the IRC server.  You could send your own PING commands to the server whilst not in any other communications to check for a live connection (Normally every 120 seconds is good).
If the server takes longer than your defined amount of time to respond to that PING command then you can attempt a reconnection. If you try and reconnect I would recommend using a disconnect method first just to make sure the bot closes all of its connections gracefully to avoid ghosting. If the attempted new connection times out then have the bot wait for a certain amount of time before trying to connect again. It might be worth limiting reconnect attempts to something like 10-15.

**Comment by MiningMark48** [comment]
Ok thanks, I will try to do something like that. How would I make it wait a certain amount of time?

**Comment by JamoBox** [comment]
Ideally you would have all of this keep-alive code being executed in its own thread. With that in mind, using thread.sleep(120000) on that thread when pausing between PINGs and the same command again with perhaps a shorter amount of time for waiting between reconnection attempts should be fine.

**Comment by MiningMark48** [comment]
Thanks, I did that, still working on it. Thanks Again.
