### ISSUE TITLE
onEvent functions

### ISSUE THREAD

**Issue by MorganEPatch** [davidlazar/PircBot#4]
PircBot v. 1.5, the documentation to which is linked as documentation for this 1.7 port, has a large number of on*() functions on the PircBot class, such as onJoin, onPart, onNickChange, onTopic, etc., which aren't supported by this version. Of particular usefulness are onJoin and onPart, which can allow the bot to automatically add a user to a system when they join the channel or to introduce itself, to serialize a user's data when they leave (users can easily leave a channel without disconnecting from a server), etc. Also of use could be the onUnknown() function, which allows the user to define their own behavior when an event occurs on the server that the PircBot framework is unable to handle.

**Comment by davidlazar** [comment]
These functions are part of the PircBot abstract class.  See [onJoin](https://github.com/davidlazar/PircBot/blob/d25ce5b4a64e7f2574525f98f846d6a7ad22c8e9/src/org/jibble/pircbot/PircBot.java#L1374) for example.
